# Generated by Django 6.0.6 on 2026-06-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        ('terceros', '0002_remove_proveedororm_identificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaFidelizacionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puntos_por_unidad', models.IntegerField(default=1)),
                ('nivel_minimo', models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Platino', 'Platino')], default='Bronce', max_length=50)),
                ('nivel_maximo', models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Platino', 'Platino')], default='Platino', max_length=50)),
                ('recompensa', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de fidelización',
                'verbose_name_plural': 'Reglas de fidelización',
                'db_table': 'warehouse_reglas_fidelizacion',
            },
        ),
        migrations.CreateModel(
            name='CanjesFidelizacionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_canjeados', models.IntegerField()),
                ('recompensa', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='terceros.clienteorm')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes_registrados', to='seguridad.usuarioorm')),
            ],
            options={
                'verbose_name': 'Canje de fidelización',
                'verbose_name_plural': 'Canjes de fidelización',
                'db_table': 'warehouse_canjes',
                'ordering': ['-fecha'],
            },
        ),
    ]
