# Generated by Django 6.0.6 on 2026-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedororm',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='proveedororm',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clienteorm',
            name='nivel_fidelidad',
            field=models.CharField(default='Bronce', max_length=50),
        ),
        migrations.AddField(
            model_name='clienteorm',
            name='puntos_fidelizacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedororm',
            name='ruc_nit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clienteorm',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clienteorm',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedororm',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
