# apps/terceros/domain/ports.py
from abc import ABC, abstractmethod
from typing import List, Optional

from .entities import ClienteDomain, ProveedorDomain


class ProveedorRepositoryPort(ABC):
    @abstractmethod
    def crear(self, p: ProveedorDomain) -> ProveedorDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[ProveedorDomain]: ...
    @abstractmethod
    def listar(self, solo_activos: bool = True) -> List[ProveedorDomain]: ...
    @abstractmethod
    def buscar(self, termino: str) -> List[ProveedorDomain]: ...
    @abstractmethod
    def actualizar(self, p: ProveedorDomain) -> ProveedorDomain: ...
    @abstractmethod
    def desactivar(self, id: int) -> None: ...


class ClienteRepositoryPort(ABC):
    @abstractmethod
    def crear(self, c: ClienteDomain) -> ClienteDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[ClienteDomain]: ...
    @abstractmethod
    def listar(self, solo_activos: bool = True) -> List[ClienteDomain]: ...
    @abstractmethod
    def buscar(self, termino: str) -> List[ClienteDomain]: ...
    @abstractmethod
    def actualizar(self, c: ClienteDomain) -> ClienteDomain: ...
    @abstractmethod
    def desactivar(self, id: int) -> None: ...
