# apps/inventario/domain/ports.py
from abc import ABC, abstractmethod
from typing import Optional, List
from .entities import CategoriaDomain, UbicacionDomain, ProductoDomain, LoteDomain


class CategoriaRepositoryPort(ABC):
    @abstractmethod
    def crear(self, cat: CategoriaDomain) -> CategoriaDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[CategoriaDomain]: ...
    @abstractmethod
    def listar(self, solo_activos: bool = True) -> List[CategoriaDomain]: ...
    @abstractmethod
    def actualizar(self, cat: CategoriaDomain) -> CategoriaDomain: ...
    @abstractmethod
    def eliminar(self, id: int) -> None: ...


class UbicacionRepositoryPort(ABC):
    @abstractmethod
    def crear(self, ub: UbicacionDomain) -> UbicacionDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[UbicacionDomain]: ...
    @abstractmethod
    def listar(self, solo_activos: bool = True) -> List[UbicacionDomain]: ...
    @abstractmethod
    def actualizar(self, ub: UbicacionDomain) -> UbicacionDomain: ...
    @abstractmethod
    def eliminar(self, id: int) -> None: ...


class ProductoRepositoryPort(ABC):
    @abstractmethod
    def crear(self, p: ProductoDomain) -> ProductoDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[ProductoDomain]: ...
    @abstractmethod
    def obtener_por_codigo(self, codigo: str) -> Optional[ProductoDomain]: ...
    @abstractmethod
    def listar(self, solo_activos: bool = True) -> List[ProductoDomain]: ...
    @abstractmethod
    def buscar(self, termino: str) -> List[ProductoDomain]: ...
    @abstractmethod
    def actualizar(self, p: ProductoDomain) -> ProductoDomain: ...
    @abstractmethod
    def actualizar_stock(self, producto_id: int, nuevo_stock: int) -> None: ...
    @abstractmethod
    def tiene_movimientos(self, producto_id: int) -> bool: ...
    @abstractmethod
    def eliminar_fisico(self, id: int) -> None: ...
    @abstractmethod
    def desactivar(self, id: int) -> None: ...


class LoteRepositoryPort(ABC):
    @abstractmethod
    def crear(self, lote: LoteDomain) -> LoteDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[LoteDomain]: ...
    @abstractmethod
    def obtener_por_producto_y_numero(self, producto_id: int, numero_lote: str) -> Optional[LoteDomain]: ...
    @abstractmethod
    def listar_por_producto_fifo(self, producto_id: int) -> List[LoteDomain]: ...
    @abstractmethod
    def actualizar_cantidad(self, lote_id: int, nueva_cantidad: int) -> None: ...
    @abstractmethod
    def desactivar(self, lote_id: int) -> None: ...
