# apps/seguridad/domain/ports.py
from abc import ABC, abstractmethod
from typing import Optional, List
from .entities import RolDomain, UsuarioDomain


class RolRepositoryPort(ABC):
    @abstractmethod
    def crear(self, rol: RolDomain) -> RolDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[RolDomain]: ...
    @abstractmethod
    def obtener_por_nombre(self, nombre: str) -> Optional[RolDomain]: ...
    @abstractmethod
    def listar(self) -> List[RolDomain]: ...
    @abstractmethod
    def actualizar(self, rol: RolDomain) -> RolDomain: ...
    @abstractmethod
    def eliminar(self, id: int) -> None: ...


class UsuarioRepositoryPort(ABC):
    @abstractmethod
    def crear(self, usuario: UsuarioDomain) -> UsuarioDomain: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> Optional[UsuarioDomain]: ...
    @abstractmethod
    def obtener_por_email(self, email: str) -> Optional[UsuarioDomain]: ...
    @abstractmethod
    def listar(self) -> List[UsuarioDomain]: ...
    @abstractmethod
    def actualizar(self, usuario: UsuarioDomain) -> UsuarioDomain: ...
    @abstractmethod
    def eliminar(self, id: int) -> None: ...
    @abstractmethod
    def guardar_token_reset(self, usuario_id: int, token: str, expiry) -> None: ...
    @abstractmethod
    def limpiar_token_reset(self, usuario_id: int) -> None: ...
