# Generated by Django 6.0.6 on 2026-06-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=200, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
                'db_table': 'warehouse_configuracion',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.IntegerField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='seguridad.usuarioorm')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'warehouse_auditoria',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='warehouse_a_entidad_0dfecc_idx'), models.Index(fields=['usuario'], name='warehouse_a_usuario_519405_idx'), models.Index(fields=['-fecha'], name='warehouse_a_fecha_47d87c_idx')],
            },
        ),
    ]
